import { getAuthedProfile } from '@/lib/actions-utils'
import { redirect, notFound } from 'next/navigation'
import Link from 'next/link'
import { createHash } from 'crypto'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { AlertTriangle, Ban } from 'lucide-react'
import { PrintButton } from '@/components/receipts/print-button'

export const metadata = {
  title: 'Contribution Receipt | FTC Pitfund',
}

interface PageProps {
  params: Promise<{ receiptNumber: string }>
}

export default async function ReceiptPage({ params }: PageProps) {
  const { receiptNumber } = await params
  const authed = await getAuthedProfile()
  if (!authed) redirect('/login')

  const { supabase } = authed

  // Fetch using the server client (respects RLS: only parties to the fulfillment or admins can read)
  const { data: receipt } = await supabase
    .from('funding_receipts')
    .select('*')
    .eq('receipt_number', receiptNumber)
    .maybeSingle()

  if (!receipt) {
    notFound()
  }

  // Verification: re-verify document hash before rendering
  const computedHash = createHash('sha256').update(receipt.document_html).digest('hex')
  const isHashValid = computedHash === receipt.document_sha256

  if (!isHashValid) {
    return (
      <div className="min-h-screen bg-muted/40 py-12 px-4 flex items-center justify-center">
        <div className="w-full max-w-xl">
          <Alert variant="destructive">
            <AlertTriangle className="h-5 w-5" />
            <AlertTitle>Tamper Warning — Verification Failed</AlertTitle>
            <AlertDescription className="mt-2 text-sm">
              This receipt document could not be verified against its security hash and will not be displayed.
              If you believe this is an error, please contact platform support.
            </AlertDescription>
          </Alert>
        </div>
      </div>
    )
  }

  // Fetch replacement receipt number if this receipt was superseded
  let replacementNumber: string | null = null
  if (receipt.superseded_by_receipt_id) {
    const { data: replacement } = await supabase
      .from('funding_receipts')
      .select('receipt_number')
      .eq('id', receipt.superseded_by_receipt_id)
      .maybeSingle()
    if (replacement?.receipt_number) {
      replacementNumber = replacement.receipt_number
    }
  }

  const isVoided = receipt.status === 'voided'

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-8 px-4 sm:px-6">
      <div className="max-w-3xl mx-auto space-y-6">
        {/* Top actions bar (hidden during print) */}
        <div className="flex items-center justify-between print:hidden">
          <Link
            href="/dashboard"
            className="text-xs text-muted-foreground hover:text-foreground underline"
          >
            ← Back to Portal
          </Link>
          <PrintButton />
        </div>

        {/* Persistent Void Banner */}
        {isVoided && (
          <Alert variant="destructive" className="print:border-destructive print:bg-destructive/10">
            <Ban className="h-5 w-5" />
            <AlertTitle className="font-bold">VOIDED RECEIPT</AlertTitle>
            <AlertDescription className="mt-1 text-sm space-y-1">
              <p>
                This receipt was voided on{' '}
                {new Date(receipt.voided_at!).toLocaleDateString('en-US', {
                  dateStyle: 'medium',
                })}
                . It is no longer valid for tax substantiation.
              </p>
              {receipt.voided_reason && (
                <p className="italic">Reason: &ldquo;{receipt.voided_reason}&rdquo;</p>
              )}
              {replacementNumber && (
                <p className="mt-2 font-medium">
                  A replacement receipt was issued: &nbsp;
                  <Link
                    href={`/receipts/${replacementNumber}`}
                    className="underline text-foreground hover:opacity-80"
                  >
                    View Receipt {replacementNumber} →
                  </Link>
                </p>
              )}
            </AlertDescription>
          </Alert>
        )}

        {/* The Document */}
        {/* Safe: HTML was generated by our server-side renderer from typed primitives, contains no script/external resource, and its SHA-256 hash was verified one line above. */}
        <div
          className="bg-white text-slate-900 rounded-lg shadow-xs border p-2 sm:p-4 print:shadow-none print:border-none print:p-0"
          dangerouslySetInnerHTML={{ __html: receipt.document_html }}
        />
      </div>
    </div>
  )
}
